#pragma once

#include "allegro5/allegro.h"

namespace hvn3::events {

	enum class EventType {
		Unspecified = -1,
		JoystickAxis = ALLEGRO_EVENT_JOYSTICK_AXIS,
		JoystickButtonDown = ALLEGRO_EVENT_JOYSTICK_BUTTON_DOWN,
		JoystickButtonUp = ALLEGRO_EVENT_JOYSTICK_BUTTON_UP,
		JoystickConfiguration = ALLEGRO_EVENT_JOYSTICK_CONFIGURATION,
		KeyDown = ALLEGRO_EVENT_KEY_DOWN,
		KeyUp = ALLEGRO_EVENT_KEY_UP,
		KeyChar = ALLEGRO_EVENT_KEY_CHAR,
		MouseAxes = ALLEGRO_EVENT_MOUSE_AXES,
		MouseButtonDown = ALLEGRO_EVENT_MOUSE_BUTTON_DOWN,
		MouseButtonUp = ALLEGRO_EVENT_MOUSE_BUTTON_UP,
		MouseWarped = ALLEGRO_EVENT_MOUSE_WARPED,
		MouseEnterDisplay = ALLEGRO_EVENT_MOUSE_ENTER_DISPLAY,
		MouseLeaveDisplay = ALLEGRO_EVENT_MOUSE_LEAVE_DISPLAY,
		TouchBegin = ALLEGRO_EVENT_TOUCH_BEGIN,
		TouchEnd = ALLEGRO_EVENT_TOUCH_END,
		TouchMove = ALLEGRO_EVENT_TOUCH_MOVE,
		TouchCancel = ALLEGRO_EVENT_TOUCH_CANCEL,
		Timer = ALLEGRO_EVENT_TIMER,
		DisplayExpose = ALLEGRO_EVENT_DISPLAY_EXPOSE,
		DisplayResize = ALLEGRO_EVENT_DISPLAY_RESIZE,
		DisplayClose = ALLEGRO_EVENT_DISPLAY_CLOSE,
		DisplayLost = ALLEGRO_EVENT_DISPLAY_LOST,
		DisplayFound = ALLEGRO_EVENT_DISPLAY_FOUND,
		DisplaySwitchOut = ALLEGRO_EVENT_DISPLAY_SWITCH_OUT,
		DisplaySwitchIn = ALLEGRO_EVENT_DISPLAY_SWITCH_IN,
		DisplayOrientation = ALLEGRO_EVENT_DISPLAY_ORIENTATION,
		DisplayHaltDrawing = ALLEGRO_EVENT_DISPLAY_HALT_DRAWING,
		DisplayResumeDrawing = ALLEGRO_EVENT_DISPLAY_RESUME_DRAWING,
		DisplayConnected = ALLEGRO_EVENT_DISPLAY_CONNECTED,
		DisplayDisconnected = ALLEGRO_EVENT_DISPLAY_DISCONNECTED,
		UserEvent = 1024 // Allegro's reserved event types stop at 1024; allows it to be directly casted to ALLEGRO_EVENT_TYPE
	};

}